import styles from '../components/Headline.module.css'
import Head from 'next/head'

export default function Headline(props) {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <div className={styles.description}>
          <p>
            Let's started by editing&nbsp;
            <code className={styles.code}>pages/{props.page}.js</code>
          </p>
        </div>
     
    </>
  )
}
